# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
#    woocommerce_api_key: '%env(WOOCOMMERCE_API_KEY)%'
#    woocommerce_api_secret: '%env(WOOCOMMERCE_API_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
        default_options:
            verify_peer: '%env(bool:IS_NEED_VERIFY_PEER)%'
            verify_host: '%env(bool:IS_NEED_VERIFY_HOST)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
when@dev:
    framework:
        http_cache: true