<?php

namespace App\Connector\Woocommerce\Repository;


use App\Core\ConnectorAbstract\Repository\RepositoryReadAbstract;
use App\Core\Iterator\AwaitingPageIterator;
use Symfony\Contracts\HttpClient\HttpClientInterface;

class CustomerRepository extends RepositoryReadAbstract
{
    public function __construct(
        private HttpClientInterface $client,
        private string $url,
        private string $key,
        private string $secret,
    )
    {
    }
    public function fetch(int $start, int $end): array
    {
        $response = $this->client->request(
            'GET',
            $this->url,
            [
                'auth_basic' => [$this->key, $this->secret],
            ]
        );
        return $response->toArray()['customers'];
    }

    public function fetchPage(int $page, int $pageSize): array
    {
        $response = $this->client->request(
            'GET',
            $this->url,
            [
                'auth_basic' => [$this->key, $this->secret],
                'query' => [
                    'page' => $page,
                    'per_page' => $pageSize,
                ],
            ]
        );
        $result = $response->toArray();
        if (empty($result)) {
            return [];
        }
        return $result['customers'];
    }

    public function createAwaitingPageIterator(
        int $startPage,
        int $pageSize = 10,
        int $jumpSize = 0,
    ): AwaitingPageIterator
    {
        if ($startPage < 1) {
            throw new \InvalidArgumentException('start page is must be more than 0 for Woocommerce api');
        }
        return parent::createAwaitingPageIterator($startPage, $pageSize, $jumpSize); // TODO: Change the autogenerated stub
    }
}