<?php declare(strict_types=1);

namespace App\Connector\Woocommerce\Factory;

use App\Connector\AbstractConnectorReadFactory;
use App\Connector\ConnectorReadType;
use Chungachanga\AbstractMigration\Connector\ConnectorFactoryReadInterface;

abstract class ConnectorFactory extends AbstractConnectorReadFactory implements ConnectorFactoryReadInterface
{
    public function createIterator(
        int $startPage,
        int $pageSize = 10,
        bool $isNeedWaitingFullPage = false,
        bool $isAllowPartialResult = true,
        int $delaySeconds = 0
    ): \Iterator
    {
        if ($startPage < 1) {
            throw new \InvalidArgumentException('start page is must be more than 0 for Woocommerce api');
        }
        return parent::createIterator($startPage, $pageSize, $isNeedWaitingFullPage, $isAllowPartialResult, $delaySeconds); // TODO: Change the autogenerated stub
    }

    public function createConnector(): ConnectorReadType
    {
        return new ConnectorReadType(
            $this->createRepository(),
            $this->createMapper(),
            $this->eventDispatcher
        );
    }
}